plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.hilt)
}

android {
    namespace 'org.singularux.music.core.permission'
    buildToolsVersion = '37.0.0'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }
    defaultConfig {
        minSdk 26
        consumerProguardFiles "consumer-rules.pro"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // AndroidX
    implementation libs.androidx.core
    // Hilt
    implementation libs.hilt.android
    annotationProcessor libs.hilt.compiler
    // Lombok
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}