plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.hilt)
    alias(libs.plugins.androidx.baselineprofile)
}

android {
    namespace = 'org.singularux.music'
    compileSdk {
        version = release(37)
    }
    buildToolsVersion = '37.0.0'
    defaultConfig {
        applicationId = 'org.singularux.music'
        minSdk = 30
        targetSdk = 37
        versionCode = 3
        versionName = '1.2.0'
    }
    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    baselineProfile {
        automaticGenerationDuringBuild = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    // Project
    api(project ':feature:nowplaying')
    api(project ':feature:playback')
    api(project ':feature:library')
    // Baseline
    implementation libs.androidx.profileinstaller
    baselineProfile(project ':baseline')
    // AndroidX
    implementation libs.androidx.core
    // Hilt
    implementation libs.hilt.android
    annotationProcessor libs.hilt.compiler
    // RxJava
    implementation libs.rxjava
}