plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.hilt)
}

android {
    namespace = 'org.singularux.music'
    buildToolsVersion = '37.0.0'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }
    defaultConfig {
        applicationId 'org.singularux.music'
        minSdk 30
        targetSdk 37
        versionCode 1
        versionName '0.1.0'
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources = true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        viewBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    api(project ':core:permission')
    api(project ':core:playback')
    api(project ':core:threading')
    api(project ':core:ui')
    implementation libs.androidx.core
    implementation libs.androidx.core.splashscreen
    implementation libs.androidx.activity
    implementation libs.google.material
    implementation libs.hilt.android
    annotationProcessor libs.hilt.compiler
    implementation libs.lifecycle.livedata
    implementation libs.lifecycle.reactivestreams
    implementation libs.lifecycle.viewmodel
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    implementation libs.media3.exoplayer
    implementation libs.media3.session
    implementation libs.picasso
    implementation libs.recyclerview
    implementation libs.rxjava
    implementation libs.rxjava.android
}