plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.hilt)
}

android {
    namespace = 'org.singularux.music.feature.nowplaying'
    compileSdk {
        version = release(37)
    }
    buildToolsVersion = '37.0.0'
    defaultConfig {
        minSdk = 26
        consumerProguardFiles 'consumer-rules.pro'
    }
    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    // Project
    api(project ':core:ui')
    api(project ':feature:playback')
    // AndroidX
    implementation libs.androidx.core
    implementation libs.androidx.activity
    // Hilt
    implementation libs.hilt.android
    annotationProcessor libs.hilt.compiler
    // Lifecycle
    implementation libs.lifecycle.livedata
    implementation libs.lifecycle.reactivestreams
    implementation libs.lifecycle.viewmodel
    // Lombok
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    // Material 3
    implementation libs.google.material
    // Media3
    implementation libs.media3.session
    // Picasso
    implementation libs.picasso
    // RxJava
    implementation libs.rxjava
}